--bài th2
CREATE DATABASE QLGiaoHang
USE QLGiaoHang

CREATE TABLE KHACHHANG(
MAKHACHHANG varchar(8) PRIMARY KEY,
TENKHACHHANG nvarchar(128) NOT NULL,
TENGIAODICH varchar(8) NOT NULL,
DIACHI nvarchar(128) NOT NULL,
EMAIL varchar(64),
DIENTHOAI varchar(10) NOT NULL,
FAX varchar(10));

CREATE TABLE NHANVIEN(
MANHANVIEN varchar(8) PRIMARY KEY,
HO nvarchar(24) NOT NULL,
TEN nvarchar(12) NOT NULL,
NGAYSINH datetime NOT NULL,
NGAYLAMVIEC datetime NOT NULL,
DIACHI nvarchar(128) NOT NULL,
DIENTHOAI varchar(10),
LUONGCOBAN float(8) ,
PHUCAP float(8));

CREATE TABLE DONDATHANG(
SOHOADON int PRIMARY KEY NOT NULL,
MAKHACHHANG varchar(8) CONSTRAINT FK_DDH_MAKHACHHANG
					   FOREIGN KEY (MAKHACHHANG)
					   REFERENCES KHACHHANG(MAKHACHHANG)
					   ON DELETE CASCADE ON UPDATE CASCADE,
MANHANVIEN varchar(8) CONSTRAINT FK_DDH_MANHANVIEN
					  FOREIGN KEY (MANHANVIEN)
					  REFERENCES NHANVIEN(MANHANVIEN)
					  ON DELETE CASCADE ON UPDATE CASCADE,
NGAYDATHANG datetime NOT NULL,
NGAYGIAOHANG datetime NOT NULL,
NGAYCHUYENHANG datetime NOT NULL,
NOIGIAOHANG nvarchar(128) NOT NULL);

CREATE TABLE NHACUNGCAP(
MACONGTY varchar(8) PRIMARY KEY,
TENCONGTY nvarchar(128) NOT NULL,
TENGIAODICH varchar(8) NOT NULL,
DIACHI nvarchar(128) NOT NULL,
DIENTHOAI varchar(10),
FAX varchar(10),
EMAIL varchar(64));


CREATE TABLE LOAIHANG(
MALOAIHANG varchar(8) PRIMARY KEY,
TENLOAIHANG nvarchar(16) NOT NULL);

CREATE TABLE MATHANG(
MAHANG varchar(8) PRIMARY KEY,
TENHANG nvarchar(16) NOT NULL,
MACONGTY varchar(8) CONSTRAINT FK_MH_MACONGTY
					FOREIGN KEY (MACONGTY)
					REFERENCES NHACUNGCAP(MACONGTY)
					ON DELETE CASCADE ON UPDATE CASCADE,
MALOAIHANG varchar(8) CONSTRAINT FK_MH_MALOAIHANG
					  FOREIGN KEY (MALOAIHANG)
					  REFERENCES LOAIHANG(MALOAIHANG)
					  ON DELETE CASCADE ON UPDATE CASCADE,
SOLUONG tinyint NOT NULL,
DONVITINH nvarchar(8) NOT NULL,
GIAHANG float(8) NOT NULL);

CREATE TABLE CHITIETDATHANG(
SOHOAHON int PRIMARY KEY
			 CONSTRAINT FK_CTDH_SOHOADON
			 FOREIGN KEY
			 REFERENCES DONDATHANG(SOHOADON) 
			 ON DELETE CASCADE ON UPDATE CASCADE,
MAHANG varchar(8) CONSTRAINT FK_CTDH_MAHANG
				  FOREIGN KEY (MAHANG)
				  REFERENCES MATHANG(MAHANG)
				  ON DELETE CASCADE ON UPDATE CASCADE,
GIABAN float(8) NOT NULL,
SOLUONG tinyint NOT NULL,
MUCGIAMGIA float(8));

DROP TABLE NHANVIEN
DROP TABLE DONDATHANG
DROP TABLE NHACUNGCAP
DROP TABLE LOAIHANG
DROP TABLE MATHANG
DROP TABLE CHITIETDATHANG
SELECT * FROM NHANVIEN
SELECT * FROM DONDATHANG
SELECT * FROM NHACUNGCAP
SELECT * FROM LOAIHANG
SELECT * FROM MATHAN
SELECT * FROM CHITIETDATHANG